### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by mayaobuduyao** [illidanlab/ABD#1]
When I reproduce the Tojan method, there is a problem "FileNotFoundError: No such file: '/home/user/ABD/backdoor_zskt/ABD_preptrained_models/triggers/trojan_wm.png' ".
What could be the problem?

**Comment by jyhong836** [comment]
The missing files could be obtained from https://github.com/VITA-Group/Trap-and-Replace-Backdoor-Defense

**Comment by mayaobuduyao** [comment]
Where is the WRN-40-2 file?

**Comment by jyhong836** [comment]
You need to follow the setup in https://github.com/illidanlab/ABD?tab=readme-ov-file#getting-started to train it by yourself.

**Comment by mayaobuduyao** [comment]
Why am I training the teacher model with high ACC and ASR, but experimenting with this code shows that the teacher model has low ACC but ASR=100%? Looks like the teacher model identified both clean and poisoned samples as backdoor targets.

**Comment by jyhong836** [comment]
Could you provide more details?
For example, which dataset, model (WRN-40-2?), and backdoor type?
Thanks

**Comment by mayaobuduyao** [comment]
> Could you provide more details? For example, which dataset, model (WRN-40-2?), and backdoor type? Thanks

Sorry for my problem, I confused the WRN code
