### ISSUE TITLE
Questions about the image used in OOD distillation

### ISSUE THREAD

**Issue by GradOpt** [illidanlab/ABD#2]
Great work!

OOD distillation seems to require a single large image. I wonder which image you used in your experiments?

Should I run the `data_generation/make_single_img_dataset.py` script from [[single-img-extrapolating](https://github.com/yukimasano/single-img-extrapolating)] to generate the OOD dataset before running the OOD distillation experiments?

**Comment by jyhong836** [comment]
Thanks for your interest in our work.

Yes. You need to generate the single image dataset and setup the path (one-image path) in [utils/config.py](https://github.com/illidanlab/ABD/blob/master/cmi/utils/config.py).

**Comment by GradOpt** [comment]
Thank you for your prompt response! Is the specific image you used the `images/ameyoko.jpg` file?

**Comment by jyhong836** [comment]
Yes. We use the default image following https://github.com/yukimasano/single-img-extrapolating/tree/master/data_generation

**Comment by GradOpt** [comment]
Thank you for your reply!
